start
progress:  0  %
progress:  0  %
486
215
475
215
464
215
479
215
484
215
485
215
463
215
458
215
446
215
462
215
450
215
481
215
58
215
368
215
246
215
244
215
282
215
358
215
362
215
333
215
328
215
321
215
196
215
360
215
330
215
259
215
310
215
356
215
194
215
215
215
128
Traceback (most recent call last):
  File "/data/humangen_kircherlab/AMIGO_TM/AMIGO/Benchmark/benchmark_data_set/PCS_data_sets/LmUGP_with_PCS/with_preassignments/8/AMIGO_non_interactive.py", line 1740, in <module>
    cli()
  File "/work/maass/.omics/mamba/envs/AMIGO/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/maass/.omics/mamba/envs/AMIGO/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/work/maass/.omics/mamba/envs/AMIGO/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/maass/.omics/mamba/envs/AMIGO/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/humangen_kircherlab/AMIGO_TM/AMIGO/Benchmark/benchmark_data_set/PCS_data_sets/LmUGP_with_PCS/with_preassignments/8/AMIGO_non_interactive.py", line 583, in cli
    print(most_unique_aa[0][0][1])
          ~~~~~~~~~~~~~~^^^
IndexError: list index out of range
fertig
